### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ghost** [henji243/ScratchVoteAnalysisTool#1]
https://github.com/henji243/ScratchVoteAnalysisTool/blob/474bda80fb052dc52e13f64212cd316718e97283/main.py#L24-L26

```python
api_responce
```
ではなく
```
api_response
```
だと思います。
わざわざ Issue で言うなっていうツッコミはなしで()

**Comment by ujex256** [comment]
あっ本当だ()
今布団の中なんで明日直します()

**Comment by ghost** [comment]
頑張れ(?)
